# Generated by Django 3.1.2 on 2021-04-14 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата действия')),
                ('action', models.TextField(default='some action', verbose_name='Действие')),
                ('device', models.TextField(blank=True, default='no info', null=True, verbose_name='Устройство')),
                ('ip', models.TextField(blank=True, default='no info', null=True, verbose_name='IP address')),
                ('location', models.TextField(blank=True, default='no info', null=True, verbose_name='Location of user')),
                ('siteOfUser', models.TextField(default='site.com', verbose_name='Сайт, откуда пришел пользователь')),
                ('userName', models.TextField(default='user', verbose_name='Имя пользователя на сайте')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=50, verbose_name='a')),
                ('b', models.CharField(max_length=50, verbose_name='b')),
                ('c', models.CharField(max_length=50, verbose_name='c')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('historyOfUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.history', verbose_name='История пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сайт пользователя')),
            ],
        ),
    ]
