# Generated by Django 3.1.2 on 2021-05-09 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20210418_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_of_site', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('text', models.TextField(verbose_name='Описание')),
                ('instruction', models.TextField(verbose_name='Инструкция')),
                ('priceGetData', models.FloatField(verbose_name='Цена за сохранение')),
                ('pricePostData', models.FloatField(verbose_name='Цена за анализ')),
                ('toSite', models.ManyToManyField(to='app.Site')),
            ],
        ),
    ]
