# Generated by Django 3.1.2 on 2021-05-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210509_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='miniText',
            field=models.CharField(default='lol', max_length=500, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tariff',
            name='toSite',
            field=models.ManyToManyField(related_name='tariff_for_site', to='app.Site'),
        ),
    ]
