# Generated by Django 3.1.2 on 2021-05-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210509_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='toSite',
        ),
        migrations.CreateModel(
            name='SiteInTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_for_site', to='app.site')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tariff')),
            ],
        ),
    ]
